# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    blog.form.registration:
       class: BlogBundle\Form\RegistrationType
       tags:
          - { name: form.type, alias: blog_user_registration }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
