blog_post:
    resource: "@BlogBundle/Resources/config/routing/post.yml"
    prefix:   /post

blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Blog:index }

blog_getpostpage:
    path:     /post/{id}
    defaults: { _controller: BlogBundle:Blog:getPost }
    requirements:
      id: \d*

blog_allpostuserpage:
    path:     /{username}/posts
    defaults: { _controller: BlogBundle:Post:index }

blog_newpostpage:
    path:     /newPost
    defaults: { _controller: BlogBundle:Post:new }

fos_user_security:
    path: /routing/security.xml
    prefix: /

fos_user_profile:
    path: routing/profile.xml
    prefix: /profile

fos_user_registration:
    path : routing/registration.xml
    prefix: /registration

fos_user_resetting:
    path: routing/resetting.xml
    prefix: /resseting

fos_user_change_password:
    path: routing/change_password.xml
    prefix: /profile
