user_auth:
    path:     /authentification
    defaults: { _controller: UserBundle:User:auth }

user_sign:
    path:     /sign
    defaults: { _controller: UserBundle:User:sign }

user_registration:
    path:     /registration
    defaults: { _controller: UserBundle:User:registration }
